# Generated by Django 3.1.6 on 2021-02-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_category'),
        ('rareapi', '0002_tag'),
    ]

    operations = [
    ]
